name:                git-move-forward
version:             0.1.0.0
github:              ilya-bobyr/git-move-forward
license:             BSD3
author:              Illia Bobyr
maintainer:          illia.bobyr@gmail.com
copyright:           2023 Illia Bobyr

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ilya-bobyr/git-move-forward#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0

default-extensions:
  - ImportQualifiedPost

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - extra
  - foldl
  - parsec
  - text
  - turtle >= 1.5.25

executables:
  git-move-forward:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - git-move-forward
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  git-move-forward-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - git-move-forward
    - hspec
    - parsec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
